### ISSUE TITLE
undefined: CELLULAR_NETWORK_FAILED_REASON

### ISSUE THREAD

**Issue by meteoricfarm** [bluenviron/gomavlib#13]
Hello Everyone,

I am using "gomavlib" in my project. But, I've met an issue recently.
Does anyone know how to solve the problem described below?

```
PS agent\cmd> go run .\main.go
# github.com/aler9/gomavlib/pkg/dialects/common
..\..\..\..\..\..\go\pkg\mod\github.com\aler9\gomavlib@v0.0.0-20211014051456-5b4257e7e03a\pkg\dialects\common\dialect.go:17730:16: undefined: CELLULAR_NETWORK_FAILED_REASON
..\..\..\..\..\..\go\pkg\mod\github.com\aler9\gomavlib@v0.0.0-20211014051456-5b4257e7e03a\pkg\dialects\common\dialect.go:17732:7: undefined: CELLULAR_NETWORK_RADIO_TYPE
```

**Comment by aler9** [comment]
Someone added CELLULAR_STATUS to the common dialect, but forgot to add CELLULAR_NETWORK_FAILED_REASON and CELLULAR_NETWORK_RADIO_TYPE.

Dialects here are automatically generated by reading XML files from the official Mavlink repository, therefore you have to open an issue here:

https://github.com/mavlink/mavlink/issues

and tell them to fix the issue.

In the meanwhile, you can use an old version of the library.

**Comment by aler9** [comment]
While waiting for the fix, the library has been rolled-back to the last working version.
