### ISSUE TITLE
bug in enum MarshalText() methods

### ISSUE THREAD

**Issue by sirno-baka** [bluenviron/gomavlib#46]
I found a bug in `MarshalText()` methods for enum 

For example, in the `common.MAV_SYS_STATUS_SENSOR` type when executing `MarshalText()`

Example:
`text, err := (common.MAV_SYS_STATUS_SENSOR_3D_GYRO | common.MAV_SYS_STATUS_SENSOR_3D_ACCEL).MarshalText()`

There will be an "invalid value" error, since the method looks at labels_MAV_SYS_STATUS_SENSOR[value] and when performing the operation | we get the value 3 without considering the bitwise operations.

I propose to return not the text, but the **value itself**.
Or if you want text there will be a method like this:

```
func label(m MAV_SYS_STATUS_SENSOR) string {
  l := []string{}
  for k, v := range labels_MAV_SYS_STATUS_SENSOR {
   if k&m == k {
    l = append(l, v)
   }
  }
  return fmt.Sprintf("%v", l)
}
```

**Comment by aler9** [comment]
fixed by #47
